WARNING_TIME=21:55
SHUTOFF_TIME=22:00
WAKEUP_TIME=06:00

# Enable/disable scheduled shutdown
ENABLED=1

# If 1, computer will power off on boot during curfew window [SHUTOFF_TIME, WAKEUP_TIME)
ENFORCE=0




